### ISSUE TITLE
AndroidViewFilterRender preview size issue

### ISSUE THREAD

**Issue by wendrawang** [pedroSG94/rtmp-rtsp-stream-client-java#439]
I'm using AndroidViewFilterRender as a filter but the preview is so big. The stream is good but the preview in phone isnt normal.

![Screenshot_20191031-210111](https://user-images.githubusercontent.com/28812033/67953530-e2c21000-fc21-11e9-822c-d29c4f27ec91.png)
(HUAT.LIVE text is cropped on top)

im using ConstraintLayout and using it like this :
`val viewRender = AndroidViewFilterRender()`

`viewRender.view = custom_view`

`rtmpCamera.glInterface.setFilter(0, viewRender)`

`custom_view` is a layout which is match parent from this screen, it has HUAT.LIVE text, description text, chinese text and also price text

i also using preview size like this:
`rtmpCamera.startPreview(CameraHelper.Facing.FRONT, 1280, 720)`

and using stream size like this:
`rtmpCamera.prepareVideo(1280, 720, 30, 1200 * 1024, false, CameraHelper.getCameraOrientation(this))`

Thanks !

**Comment by pedroSG94** [comment]
The preview and stream will get same result with filters.
The difference is only that stream have 1280x720 px and preview will have this resolution scaled to fill device screen so you can see the filter higher than stream.
If you can see that your filter don't have a good aspect ratio this should be because you forget set keepAspect ratio in preview:
```xml
<com.pedro.rtplibrary.view.OpenGlView
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:id="@+id/surfaceView"
//this is the line
      app:keepAspectRatio="true"
      />
```

**Comment by wendrawang** [comment]
i already turn on that `keepAspectRatio` to true, and that issue is happen.

**Comment by pedroSG94** [comment]
So the problem is aspect ratio, right?. In this case:
Can you share an activity code to reproduce? (xml and java/kotlin class)
If you can't. Share me a screenshoot of preview and stream to see the difference.

**Comment by wendrawang** [comment]
Preview on phone :
![photo6199404637870729437](https://user-images.githubusercontent.com/28812033/68118811-8158b480-ff33-11e9-8b55-6ce997bbcc7a.jpg)

Streaming :
![Screen Shot 2019-11-04 at 18 44 55](https://user-images.githubusercontent.com/28812033/68118826-92092a80-ff33-11e9-989d-31d6830dcdb6.png)

i'm using the structure like this :
ConstraintLayout as a root view
   -ConstraintLayout (has textview and imageview inside) as a custom_view
   -com.pedro.rtplibrary.view.OpenGlView

**Comment by pedroSG94** [comment]
Preview seems cropped in top, but aspect ratio is working fine (custom view is not deformed).
I will try reproduce your error, but maybe I need more info about textview and imageview to reproduce your error, like view size, padding, margin, position, etc.

**Comment by wendrawang** [comment]
`<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
                                                   xmlns:app="http://schemas.android.com/apk/res-auto"
                                                   android:id="@+id/activity_example_rtmp"
                                                   android:layout_width="match_parent"
                                                   android:layout_height="match_parent"
>
    <androidx.constraintlayout.widget.ConstraintLayout
            android:id="@+id/custom_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
    >
        <ImageView
                android:id="@+id/logo_img"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                app:layout_constraintWidth_percent="0.3"
                android:adjustViewBounds="true"
                android:src="@drawable/logo_appname"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                android:layout_marginTop="20dp"
                android:layout_marginRight="15dp"
        />

        <LinearLayout
                android:id="@+id/temp_chinese_txt_layout"
                android:layout_width="wrap_content"
                android:layout_height="0dp"
                app:layout_constraintTop_toBottomOf="@id/logo_img"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintRight_toRightOf="parent"
                android:layout_marginRight="10dp"
                android:layout_marginTop="10dp"
                android:orientation="horizontal"
        >
            <View
                    android:id="@+id/additional_margin"
                    android:layout_width="5dp"
                    android:layout_height="match_parent"/>
            <TextView
                    android:id="@+id/chinese_txt"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="你\n的\n劲\n爆\n产\n品\n标\n题"
                    android:textColor="@color/white"
                    android:textSize="32sp"
                    android:textAlignment="center"
                    android:shadowColor="@color/black"
                    android:shadowRadius="10"
                    android:shadowDx="1"
                    android:shadowDy="1"
                    android:fontFamily="@font/chinese_font"
            />
        </LinearLayout>

        <TextView
                android:id="@+id/english_txt"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:text="THIS IS YOUR AWESOME PRODUCT TITLE"
                android:textColor="@color/white"
                android:textSize="25sp"
                android:textAlignment="textEnd"
                android:shadowColor="@color/black"
                android:shadowRadius="10"
                android:shadowDx="1"
                android:shadowDy="1"
                app:layout_constraintTop_toBottomOf="@id/logo_img"
                app:layout_constraintRight_toLeftOf="@id/temp_chinese_txt_layout"
                app:layout_constraintLeft_toLeftOf="parent"
                android:fontFamily="@font/english_font"
                android:layout_marginRight="5dp"
                android:layout_marginLeft="10dp"
                android:layout_marginTop="10dp"
        />

        <LinearLayout
                android:id="@+id/layout_price"
                android:layout_width="100dp"
                android:layout_height="40dp"
                app:layout_constraintTop_toBottomOf="@id/english_txt"
                app:layout_constraintRight_toLeftOf="@id/temp_chinese_txt_layout"
                android:layout_marginTop="15dp"
                android:layout_marginRight="5dp"
                android:background="@color/white"
                android:gravity="center"
        >
            <TextView
                    android:id="@+id/price_txt"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:fontFamily="@font/english_font"
                    android:textColor="@color/black"
                    android:text="$99.99"
                    android:textSize="25sp"
            />
        </LinearLayout>

    </androidx.constraintlayout.widget.ConstraintLayout>

    <com.pedro.rtplibrary.view.OpenGlView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:id="@+id/surfaceView"
            app:keepAspectRatio="true"
            app:numFilters="9"
            app:AAEnabled="false"
    />
</androidx.constraintlayout.widget.ConstraintLayout>
`

**Comment by wendrawang** [comment]
i did fullscreen with this
`requestWindowFeature(Window.FEATURE_NO_TITLE)
supportActionBar?.hide()
window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
window.setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN)`

i'm using Motorola G5s plus

this is my full view xml :
https://pastecode.xyz/view/94596b44 (deleted in 1 week)

**Comment by pedroSG94** [comment]
As you can see I can't reproduce your problem (Obviously I replaced your icons with a random icons).
![Screenshot_20191106-160056](https://user-images.githubusercontent.com/17556876/68309702-1af8a100-00af-11ea-9688-9175132a9be8.jpg)
Can you do it to try reproduce your case?
- Open my project example. In app module:
Replace layout "activity_example.xml" to:
```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/activity_example_rtmp"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    >
  <androidx.constraintlayout.widget.ConstraintLayout
      android:id="@+id/custom_view"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      >
    <ImageView
        android:id="@+id/logo_img"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:layout_constraintWidth_percent="0.3"
        android:adjustViewBounds="true"
        android:src="@drawable/icon_microphone_off"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        android:layout_marginTop="20dp"
        android:layout_marginRight="15dp"
        />

    <LinearLayout
        android:id="@+id/temp_chinese_txt_layout"
        android:layout_width="wrap_content"
        android:layout_height="0dp"
        app:layout_constraintTop_toBottomOf="@id/logo_img"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        android:layout_marginRight="10dp"
        android:layout_marginTop="10dp"
        android:orientation="horizontal"
        >
      <View
          android:id="@+id/additional_margin"
          android:layout_width="5dp"
          android:layout_height="match_parent"/>
      <TextView
          android:id="@+id/chinese_txt"
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"
          android:text="你\n的\n劲\n爆\n产\n品\n标\n题"
          android:textColor="@color/white"
          android:textSize="32sp"
          android:textAlignment="center"
          android:shadowColor="@color/black"
          android:shadowRadius="10"
          android:shadowDx="1"
          android:shadowDy="1"
          />
    </LinearLayout>

    <TextView
        android:id="@+id/english_txt"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:text="THIS IS YOUR AWESOME PRODUCT TITLE"
        android:textColor="@color/white"
        android:textSize="25sp"
        android:textAlignment="textEnd"
        android:shadowColor="@color/black"
        android:shadowRadius="10"
        android:shadowDx="1"
        android:shadowDy="1"
        app:layout_constraintTop_toBottomOf="@id/logo_img"
        app:layout_constraintRight_toLeftOf="@id/temp_chinese_txt_layout"
        app:layout_constraintLeft_toLeftOf="parent"
        android:layout_marginRight="5dp"
        android:layout_marginLeft="10dp"
        android:layout_marginTop="10dp"
        />

    <LinearLayout
        android:id="@+id/layout_price"
        android:layout_width="100dp"
        android:layout_height="40dp"
        app:layout_constraintTop_toBottomOf="@id/english_txt"
        app:layout_constraintRight_toLeftOf="@id/temp_chinese_txt_layout"
        android:layout_marginTop="15dp"
        android:layout_marginRight="5dp"
        android:background="@color/white"
        android:gravity="center"
        >
      <TextView
          android:id="@+id/price_txt"
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"
          android:textColor="@color/black"
          android:text="$99.99"
          android:textSize="25sp"
          />
    </LinearLayout>

  </androidx.constraintlayout.widget.ConstraintLayout>

  <com.pedro.rtplibrary.view.OpenGlView
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:id="@+id/surfaceView"
      app:keepAspectRatio="true"
      app:numFilters="9"
      app:AAEnabled="false"
      />

  <LinearLayout
      android:layout_width="match_parent"
      android:layout_height="170dp"
      app:layout_constraintBottom_toBottomOf="parent"
      android:background="@color/black"
      android:alpha="0.3"
      android:orientation="vertical"
      />

  <LinearLayout
      android:id="@+id/layout_center"
      android:layout_width="match_parent"
      android:layout_height="70dp"
      android:orientation="horizontal"
      android:layout_marginLeft="20dp"
      android:layout_marginRight="20dp"
      app:layout_constraintBottom_toTopOf="@id/layout_bottom"
      android:gravity="center"
      android:weightSum="4"
      >
    <LinearLayout
        android:id="@+id/btn_addtext"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1"
        android:gravity="center"
        >
      <ImageView
          android:id="@+id/img_addtext"
          android:layout_width="30dp"
          android:layout_height="30dp"
          android:src="@drawable/icon_camera_off"
          android:tint="#fff000"
          />
    </LinearLayout>

    <LinearLayout
        android:id="@+id/btn_comment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1"
        android:gravity="center"
        >
      <ImageView
          android:layout_width="30dp"
          android:layout_height="30dp"
          android:src="@drawable/icon_camera_off"
          android:tint="@color/white"
          />
    </LinearLayout>

    <LinearLayout
        android:id="@+id/btn_addbeautyeffect"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1"
        android:gravity="center"
        >
      <ImageView
          android:id="@+id/img_addbeautyeffect"
          android:layout_width="30dp"
          android:layout_height="30dp"
          android:src="@drawable/icon_camera_off"
          android:tint="#fff000"
          />
    </LinearLayout>

    <LinearLayout
        android:id="@+id/btn_changecamera"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1"
        android:gravity="center"
        >
      <ImageView
          android:layout_width="30dp"
          android:layout_height="30dp"
          android:src="@drawable/icon_camera_off"
          android:tint="@color/white"
          />
    </LinearLayout>

  </LinearLayout>

  <LinearLayout
      android:id="@+id/layout_bottom"
      android:layout_width="match_parent"
      android:layout_height="80dp"
      android:orientation="horizontal"
      android:layout_marginBottom="20dp"
      app:layout_constraintBottom_toBottomOf="parent"
      android:gravity="center"
      android:weightSum="1"
      >

    <LinearLayout
        android:id="@+id/btn_start_stop_stream"
        android:layout_width="match_parent"
        android:layout_height="60dp"
        android:layout_marginLeft="40dp"
        android:layout_marginRight="40dp"
        android:background="@drawable/icon_camera"
        android:gravity="center"
        >
      <TextView
          android:id="@+id/txt_btn_start_stop"
          android:layout_width="match_parent"
          android:layout_height="wrap_content"
          android:text="Go Live on Facebook"
          android:textAlignment="center"
          android:layout_marginLeft="20dp"
          android:layout_marginRight="20dp"
          android:textColor="#fff000"
          android:textSize="20sp"
          />
    </LinearLayout>
  </LinearLayout>

  <LinearLayout
      android:id="@+id/beauty_filter_layout"
      android:layout_width="match_parent"
      android:layout_height="190dp"
      app:layout_constraintBottom_toBottomOf="parent"
      android:background="@color/white"
      android:orientation="vertical"
      android:gravity="center"
      android:weightSum="2"
      android:visibility="gone"
      >
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:layout_weight="1"
        android:gravity="center"
        >
      <TextView
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"
          android:text="Smooth"
          />

      <SeekBar android:layout_width="match_parent"
          android:layout_height="wrap_content"
          android:layout_margin="10dp"
          android:max="100"
          android:id="@+id/grind_slider"
          />
    </LinearLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:layout_weight="1"
        android:gravity="center"
        >
      <TextView
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"
          android:text="Whiten"
          />

      <SeekBar android:layout_width="match_parent"
          android:layout_height="wrap_content"
          android:layout_margin="10dp"
          android:max="100"
          android:id="@+id/whiten_slider"
          />
    </LinearLayout>
  </LinearLayout>

  <LinearLayout
      android:id="@+id/livecomment_view"
      android:layout_width="match_parent"
      android:layout_height="0dp"
      app:layout_constraintHeight_percent="0.5"
      android:background="@color/white"
      android:orientation="vertical"
      app:layout_constraintBottom_toBottomOf="parent"
      android:visibility="gone"
      >
    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="#fff000"
        android:elevation="6dp"
        >
      <LinearLayout
          android:id="@+id/backcomment_btn"
          android:layout_width="?attr/actionBarSize"
          android:layout_height="match_parent"
          app:layout_constraintLeft_toLeftOf="parent"
          app:layout_constraintTop_toTopOf="parent"
          android:gravity="center"
          >
        <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/icon_menu"
            />
      </LinearLayout>

      <TextView
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"
          app:layout_constraintLeft_toRightOf="@id/backcomment_btn"
          app:layout_constraintTop_toTopOf="parent"
          app:layout_constraintBottom_toBottomOf="parent"
          android:text="Live Comments"
          android:textSize="18sp"
          android:textColor="@color/white"
          />

      <LinearLayout
          android:id="@+id/refreshcomment_btn"
          android:layout_width="?attr/actionBarSize"
          android:layout_height="match_parent"
          app:layout_constraintRight_toRightOf="parent"
          app:layout_constraintTop_toTopOf="parent"
          android:gravity="center"
          >
        <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/icon_menu"
            />
      </LinearLayout>

      <LinearLayout
          android:id="@+id/sharecomment_btn"
          android:layout_width="?attr/actionBarSize"
          android:layout_height="match_parent"
          app:layout_constraintRight_toLeftOf="@id/refreshcomment_btn"
          app:layout_constraintTop_toTopOf="parent"
          android:gravity="center"
          >
        <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/icon_microphone"
            />
      </LinearLayout>
    </androidx.constraintlayout.widget.ConstraintLayout>

    <WebView
        android:id="@+id/livecomment_webview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        />
  </LinearLayout>

  <androidx.constraintlayout.widget.ConstraintLayout
      android:id="@+id/subscription_view"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:background="@color/white"
      android:orientation="vertical"
      android:visibility="gone"
      >

    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/header_subs"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="#fff000"
        android:elevation="6dp"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        >
      <LinearLayout
          android:id="@+id/backsubcription_btn"
          android:layout_width="?attr/actionBarSize"
          android:layout_height="match_parent"
          app:layout_constraintLeft_toLeftOf="parent"
          app:layout_constraintTop_toTopOf="parent"
          android:gravity="center"
          >
        <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/icon_menu"
            />
      </LinearLayout>

      <TextView
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"
          app:layout_constraintLeft_toLeftOf="parent"
          app:layout_constraintRight_toRightOf="parent"
          app:layout_constraintTop_toTopOf="parent"
          app:layout_constraintBottom_toBottomOf="parent"
          android:text="Huat.live Subscription"
          android:textSize="18sp"
          android:textColor="@color/white"
          />
    </androidx.constraintlayout.widget.ConstraintLayout>

    <TextView
        android:id="@+id/text_bold1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="@id/header_subs"
        android:text="14 days free trial, only SGD$990/\nmonth after"
        android:textSize="18sp"
        android:textColor="@color/black"
        android:textStyle="bold"
        android:textAlignment="center"
        android:layout_marginTop="30dp"
        />

    <TextView
        android:id="@+id/text_light1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="@id/text_bold1"
        android:text="No commitment. Cancel anytime"
        android:textSize="18sp"
        android:textColor="@color/black"
        android:textStyle="normal"
        android:layout_marginTop="10dp"
        />

    <View
        android:id="@+id/line1"
        android:layout_width="match_parent"
        android:layout_height="2dp"
        android:background="#d0d0d0"
        app:layout_constraintTop_toBottomOf="@id/text_light1"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        android:layout_marginTop="20dp"
        android:layout_marginLeft="30dp"
        android:layout_marginRight="30dp"
        />

    <TextView
        android:id="@+id/text_light2"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:layout_constraintLeft_toLeftOf="@id/line1"
        app:layout_constraintRight_toRightOf="@id/line1"
        app:layout_constraintTop_toBottomOf="@id/line1"
        android:text="* Enjoy Live Broadcast to your Pages\n* Unlimited Live Activities"
        android:textSize="18sp"
        android:textColor="@color/black"
        android:textStyle="normal"
        android:layout_marginTop="10dp"
        />

    <TextView
        android:id="@+id/text_light3"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintLeft_toLeftOf="@id/line1"
        app:layout_constraintRight_toRightOf="@id/line1"
        app:layout_constraintTop_toBottomOf="@id/text_light2"
        app:layout_constraintBottom_toTopOf="@id/tos_layout"
        android:text="Users will be charged SGD$990/month after 14 days free trial ends. The first subscription date will automatically start on the day after 14 days free trial ends if you do not cancel the subscription.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Platea dictumst quisque sagittis purus sit amet volutpat. Nunc aliquet bibendum enim facilisis gravida. Velit ut tortor pretium viverra suspendisse potenti nullam. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Porttitor rhoncus dolor purus non enim. Faucibus a pellentesque sit amet porttitor eget dolor. Enim neque volutpat ac tincidunt vitae. Et odio pellentesque diam volutpat commodo sed egestas egestas. Risus feugiat in ante metus dictum at tempor commodo. Non tellus orci ac auctor augue mauris augue neque gravida. In massa tempor nec feugiat nisl pretium fusce id velit. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Enim blandit volutpat maecenas volutpat blandit aliquam. Nisl suscipit adipiscing bibendum est ultricies integer quis. Gravida cum sociis natoque penatibus et magnis dis. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Ut venenatis tellus in metus.\n\nPharetra pharetra massa massa ultricies. Nulla pharetra diam sit amet nisl suscipit adipiscing. In pellentesque massa placerat duis ultricies. Luctus venenatis lectus magna fringilla urna porttitor. Quis vel eros donec ac odio tempor. Sem viverra aliquet eget sit amet. Risus nullam eget felis eget. Elementum curabitur vitae nunc sed. Euismod nisi porta lorem mollis aliquam ut porttitor leo a. Ultrices dui sapien eget mi proin sed libero enim sed. Vitae ultricies leo integer malesuada nunc. Risus nec feugiat in fermentum. Sed libero enim sed faucibus turpis in eu. Felis imperdiet proin fermentum leo vel. Molestie a iaculis at erat. Leo in vitae turpis massa."
        android:textSize="18sp"
        android:textColor="@color/black"
        android:textStyle="normal"
        android:scrollbars="vertical"
        android:layout_marginTop="10dp"
        android:layout_marginBottom="20dp"
        />

    <LinearLayout
        android:id="@+id/tos_layout"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:layout_constraintLeft_toLeftOf="@id/line1"
        app:layout_constraintRight_toRightOf="@id/line1"
        app:layout_constraintBottom_toTopOf="@id/subs_btn"
        android:layout_marginBottom="30dp"
        android:orientation="horizontal"
        android:gravity="center_vertical"
        >
      <CheckBox
          android:id="@+id/cb_tos"
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"
          />

      <TextView
          android:id="@+id/agreement_txt"
          android:layout_width="match_parent"
          android:layout_height="wrap_content"
          android:text="I have read and agree Huat.live's Terms of Service and Privacy Policy"
          android:textSize="16sp"
          android:textColor="@color/black"
          android:textColorLink="@color/black"
          android:textColorHighlight="@android:color/transparent"
          android:alpha="0.7"
          android:textStyle="normal"
          android:layout_marginLeft="10dp"
          />
    </LinearLayout>

    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/subs_btn"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="@color/black"
        android:elevation="6dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        >
      <TextView
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"
          app:layout_constraintLeft_toLeftOf="parent"
          app:layout_constraintRight_toRightOf="parent"
          app:layout_constraintTop_toTopOf="parent"
          app:layout_constraintBottom_toBottomOf="parent"
          android:text="Subscribe"
          android:textSize="18sp"
          android:textColor="@color/white"
          />
    </androidx.constraintlayout.widget.ConstraintLayout>
  </androidx.constraintlayout.widget.ConstraintLayout>
</androidx.constraintlayout.widget.ConstraintLayout>
```
Replace ExampleRtmpAcitivity class to:
```java
package com.pedro.rtpstreamer.defaultexample;

import android.os.Build;
import android.os.Bundle;
import android.os.Environment;
import android.view.SurfaceHolder;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;
import com.pedro.encoder.input.gl.render.filters.AndroidViewFilterRender;
import com.pedro.encoder.input.video.CameraOpenException;
import com.pedro.rtplibrary.rtmp.RtmpCamera1;
import com.pedro.rtplibrary.view.OpenGlView;
import com.pedro.rtpstreamer.R;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import net.ossrs.rtmp.ConnectCheckerRtmp;

/**
 * More documentation see:
 * {@link com.pedro.rtplibrary.base.Camera1Base}
 * {@link com.pedro.rtplibrary.rtmp.RtmpCamera1}
 */
public class ExampleRtmpActivity extends AppCompatActivity
    implements ConnectCheckerRtmp, View.OnClickListener, SurfaceHolder.Callback {

  private RtmpCamera1 rtmpCamera1;
  //private Button button;
  //private Button bRecord;
  //private EditText etUrl;

  private String currentDateAndTime = "";
  private File folder = new File(Environment.getExternalStorageDirectory().getAbsolutePath()
      + "/rtmp-rtsp-stream-client-java");

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
    fullScreen();
    setContentView(R.layout.activity_example);
    OpenGlView surfaceView = findViewById(R.id.surfaceView);
    //button = findViewById(R.id.b_start_stop);
    //button.setOnClickListener(this);
    //bRecord = findViewById(R.id.b_record);
    //bRecord.setOnClickListener(this);
    //Button switchCamera = findViewById(R.id.switch_camera);
    //switchCamera.setOnClickListener(this);
    //etUrl = findViewById(R.id.et_rtp_url);
    //etUrl.setHint(R.string.hint_rtmp);
    rtmpCamera1 = new RtmpCamera1(surfaceView, this);
    rtmpCamera1.setReTries(10);
    surfaceView.getHolder().addCallback(this);
  }

  private void fullScreen() {
    requestWindowFeature(Window.FEATURE_NO_TITLE);
    getSupportActionBar().hide();
    getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
    getWindow().setFlags(
        WindowManager.LayoutParams.FLAG_FULLSCREEN,
        WindowManager.LayoutParams.FLAG_FULLSCREEN);
  }

  @Override
  public void onConnectionSuccessRtmp() {
    runOnUiThread(new Runnable() {
      @Override
      public void run() {
        Toast.makeText(ExampleRtmpActivity.this, "Connection success", Toast.LENGTH_SHORT).show();
      }
    });
  }

  @Override
  public void onConnectionFailedRtmp(final String reason) {
    runOnUiThread(new Runnable() {
      @Override
      public void run() {
        if (rtmpCamera1.shouldRetry(reason)) {
          Toast.makeText(ExampleRtmpActivity.this, "Retry", Toast.LENGTH_SHORT)
              .show();
          rtmpCamera1.reTry(5000);  //Wait 5s and retry connect stream
        } else {
          Toast.makeText(ExampleRtmpActivity.this, "Connection failed. " + reason, Toast.LENGTH_SHORT)
              .show();
          rtmpCamera1.stopStream();
          //button.setText(R.string.start_button);
        }
      }
    });
  }

  @Override
  public void onNewBitrateRtmp(long bitrate) {

  }

  @Override
  public void onDisconnectRtmp() {
    runOnUiThread(new Runnable() {
      @Override
      public void run() {
        Toast.makeText(ExampleRtmpActivity.this, "Disconnected", Toast.LENGTH_SHORT).show();
      }
    });
  }

  @Override
  public void onAuthErrorRtmp() {
    runOnUiThread(new Runnable() {
      @Override
      public void run() {
        Toast.makeText(ExampleRtmpActivity.this, "Auth error", Toast.LENGTH_SHORT).show();
      }
    });
  }

  @Override
  public void onAuthSuccessRtmp() {
    runOnUiThread(new Runnable() {
      @Override
      public void run() {
        Toast.makeText(ExampleRtmpActivity.this, "Auth success", Toast.LENGTH_SHORT).show();
      }
    });
  }

  @Override
  public void onClick(View view) {
    switch (view.getId()) {
      case R.id.b_start_stop:
        if (!rtmpCamera1.isStreaming()) {
          if (rtmpCamera1.isRecording()
              || rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo()) {
            //button.setText(R.string.stop_button);
            //rtmpCamera1.startStream(etUrl.getText().toString());
          } else {
            Toast.makeText(this, "Error preparing stream, This device cant do it",
                Toast.LENGTH_SHORT).show();
          }
        } else {
          //button.setText(R.string.start_button);
          rtmpCamera1.stopStream();
        }
        break;
      case R.id.switch_camera:
        try {
          rtmpCamera1.switchCamera();
        } catch (CameraOpenException e) {
          Toast.makeText(this, e.getMessage(), Toast.LENGTH_SHORT).show();
        }
        break;
      case R.id.b_record:
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
          if (!rtmpCamera1.isRecording()) {
            try {
              if (!folder.exists()) {
                folder.mkdir();
              }
              SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault());
              currentDateAndTime = sdf.format(new Date());
              if (!rtmpCamera1.isStreaming()) {
                if (rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo()) {
                  rtmpCamera1.startRecord(
                      folder.getAbsolutePath() + "/" + currentDateAndTime + ".mp4");
                  //bRecord.setText(R.string.stop_record);
                  Toast.makeText(this, "Recording... ", Toast.LENGTH_SHORT).show();
                } else {
                  Toast.makeText(this, "Error preparing stream, This device cant do it",
                      Toast.LENGTH_SHORT).show();
                }
              } else {
                rtmpCamera1.startRecord(
                    folder.getAbsolutePath() + "/" + currentDateAndTime + ".mp4");
                //bRecord.setText(R.string.stop_record);
                Toast.makeText(this, "Recording... ", Toast.LENGTH_SHORT).show();
              }
            } catch (IOException e) {
              rtmpCamera1.stopRecord();
              //bRecord.setText(R.string.start_record);
              Toast.makeText(this, e.getMessage(), Toast.LENGTH_SHORT).show();
            }
          } else {
            rtmpCamera1.stopRecord();
            //bRecord.setText(R.string.start_record);
            Toast.makeText(this,
                "file " + currentDateAndTime + ".mp4 saved in " + folder.getAbsolutePath(),
                Toast.LENGTH_SHORT).show();
            currentDateAndTime = "";
          }
        } else {
          Toast.makeText(this, "You need min JELLY_BEAN_MR2(API 18) for do it...",
              Toast.LENGTH_SHORT).show();
        }
        break;
      default:
        break;
    }
  }

  @Override
  public void surfaceCreated(SurfaceHolder surfaceHolder) {

  }

  @Override
  public void surfaceChanged(SurfaceHolder surfaceHolder, int i, int i1, int i2) {
    rtmpCamera1.startPreview(1280, 720);
    AndroidViewFilterRender androidViewFilterRender = new AndroidViewFilterRender();
    androidViewFilterRender.setView(findViewById(R.id.custom_view));
    rtmpCamera1.getGlInterface().setFilter(androidViewFilterRender);
  }

  @Override
  public void surfaceDestroyed(SurfaceHolder surfaceHolder) {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2 && rtmpCamera1.isRecording()) {
      rtmpCamera1.stopRecord();
      //bRecord.setText(R.string.start_record);
      Toast.makeText(this,
          "file " + currentDateAndTime + ".mp4 saved in " + folder.getAbsolutePath(),
          Toast.LENGTH_SHORT).show();
      currentDateAndTime = "";
    }
    if (rtmpCamera1.isStreaming()) {
      rtmpCamera1.stopStream();
      //button.setText(getResources().getString(R.string.start_button));
    }
    rtmpCamera1.stopPreview();
  }
}
```
Add constraintlayout to app module dependencies
```xml
  implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
```
Compile and install app in your device and open Default RTMP. The result expected is image previously attached.

If you problem persists:
Go to this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlView.java#L129
Add this Log (without delete, only add it after):
```java
Log.e("Debug", "preview: " + previewWidth + "x" + previewHeight + ", encoder: " + encoderWidth + "x" + encoderHeight);
```
Start a stream and show me logcat result.

**Comment by wendrawang** [comment]
I try using my own layout and code, and debug it manually (without adding logger), i've got :
```
encoderHeight = 1280
encoderWidth = 720
previewHeight = 1776
previewWidth = 1080
```

and also i found `surfaceManagerEncoder` is null

**Comment by pedroSG94** [comment]
Preview and encoder resolution seems fine and surfaceManagerEncoder is null if you are not recording or streaming so all is normal.
Since I can't reproduce your issue in Samsung S7 I will try with others devices. Also, if you can, try with others devices to confirm to know if other models is affected

**Comment by wendrawang** [comment]
I think this is pure a preview bug on the library code.
I'm using on Motorola G5s Plus and Redmi Note 5, that bug is happen.
and when i try using Xiaomi Mi A1, there is no issue about that.
and also i trying using Samsung Galaxy S9, there is no issue but its not be fullscreen

![photo6208477459930786119](https://user-images.githubusercontent.com/28812033/68458576-b7e54680-0235-11ea-8687-a8f1bdda37f0.jpg)

**Comment by pedroSG94** [comment]
I think aspect ratio is not related. I tested with Xiaomi A2 (1080x2160) and huawei P8 lite 2017 (1080x1920). Both devices is working fine. Also I tested with differents emulators with differents aspect ratio and all is working fine. 
Also I tested set same view size that you get with your test (1080x1776) but all is working.

Maybe the problem is with motorola devices and xiaomi devices running MIUI. I will try get one of this devices and test it.

**Comment by pedroSG94** [comment]
I tested with Moto G4 but all is working fine. I will try reproduce it  by other way

**Comment by pedroSG94** [comment]
Ok, finally I detected the problem. 
Canvas from filter should has different scale in preview and in stream result. I'm working in the fix

**Comment by pedroSG94** [comment]
This should be fixed here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/8dcfb87dd8b99b6d51b110fc0e9959adb71fd8c4
Test it and let me know if it is working for you.

**Comment by wendrawang** [comment]
can you release it so i can test it? because i'm using older Android Studio and i cant update it because its my office policy, thanks !

**Comment by pedroSG94** [comment]
Try this:
implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:8dcfb87dd8'

**Comment by wendrawang** [comment]
I test in my Motorola G5s plus with bottom navigation turned on, it still happen.
If i turn it off, it runs well.
In Motorola G5s plus, has a feature we can turn on or turn off bottom navigation (any soft keys like back button, home button)

With bottom navigation turned on :
![Screenshot_20191111-212727](https://user-images.githubusercontent.com/28812033/68594565-69040f00-04ca-11ea-946e-5122d3702f99.png)

With bottom navigation turned off :
![Screenshot_20191111-212709](https://user-images.githubusercontent.com/28812033/68594536-55f13f00-04ca-11ea-9051-71d891773bbd.png)

The special menu :
![Screenshot_20191111-212752~2](https://user-images.githubusercontent.com/28812033/68594546-5d184d00-04ca-11ea-8335-9e4152584e22.png)

I'll test tomorrow on my office phone (Redmi Note 5) which cant turn off the bottom navigation.
Will update you tomorrow :D

**Comment by pedroSG94** [comment]
Try with this commit:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/9839512cbb295bd7c2cce7c4dc2e8cb34fc9d584

implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:previewfiltertest-SNAPSHOT'

**Comment by wendrawang** [comment]
it still happen in my phone
on redmi 5 it doesnt happen

can i know how to automatically add the preview resolution based on any phone?
because the default is 640x480
and i dont know how to set it automatically base on phone screen.
if i set it fix 720x1280, on galaxy s9 it will be smaller
